Repository WildCodeSchool/lyon-js-sept-2020-g2, pull requests merged in 2020-11, with the labels that each got.

#34 Contact form
  package-lock.json
  src/components/ContactForm.js
  src/components/ContactForm.scss
  src/components/Home.js
Labels: Ready for prod

#50 Us re05 map mobile
  package-lock.json
  package.json
  src/components/DataByCounty.scss
  src/components/Home.js
  src/components/Map.js
  src/components/Map.scss
  src/components/News.js
Labels: Ready for prod

#52 Top 5 county cards
  package-lock.json
  package.json
  src/components/DataCard.js
  src/components/TopFive.js
  src/components/TopFive.scss
  src/components/TopFiveCard.js
  src/components/WhereToGo.js
  src/components/WhereToGo.scss
  src/components/countyList.json
  src/components/prefectures.json
  src/drees_lits_reanimation_2013-2018.xlsx
Labels: Ready for prod

#51 Re 04 auto complete field
  .eslintrc.json
  package-lock.json
  package.json
  src/components/DataByCounty.js
  src/components/SearchBar.js
Labels: Fixed - ready for prod

#54 Nav05 style
  src/App.js
  src/Global.css
  src/components/Burger.js
  src/components/ContactForm.js
  src/components/DataByCounty.js
  src/components/Footer.js
  src/components/Home.js
  src/components/Map.js
  src/components/Navbar.js
  src/components/News.js
  src/components/SearchBar.js
  src/components/TopFive.js
  src/components/TopFiveCard.js
  src/components/WhereToGo.js
  src/components/datas/countyList.json
  src/components/datas/prefectures.json
  src/components/img/facebook-logo.png
  src/components/img/github-logo.png
  src/components/img/gouvernement-logo.png
  src/components/img/logo.png
  src/components/img/twitter-logo.png
  src/components/style/Burger.scss
  src/components/style/ContactForm.scss
  src/components/style/DataByCounty.scss
  src/components/style/Footer.scss
  src/components/style/Global.css
  src/components/style/Map.scss
  src/components/style/Navbar.scss
  src/components/style/News.scss
  src/components/style/TopFive.scss
  src/components/style/WhereToGo.scss
  src/drees_lits_reanimation_2013-2018.xlsx
  src/index.css
  src/index.js
  src/pictures/logo.png
Labels: Ready for validation

#55 Last fixes sprint2
  .vscode/settings.json
  package-lock.json
  package.json
  public/index.html
  src/App.js
  src/App.scss
  src/components/Burger.js
  src/components/DataByCounty.js
  src/components/DataCard.js
  src/components/Footer.js
  src/components/Navbar.js
  src/components/TopFive.js
  src/components/TopFiveCard.js
  src/components/style/Burger.scss
  src/components/style/ContactForm.scss
  src/components/style/DataByCounty.scss
  src/components/style/Footer.scss
  src/components/style/Global.css
  src/components/style/Navbar.scss
  src/components/style/News.scss
Labels: Ready for validation

#66 Bannière d'accueil
  src/components/Banner.js
  src/components/Home.js
  src/components/img/face-mask-banner.png
  src/components/img/face-mask-banner1.png
  src/components/style/Banner.scss
  src/components/style/Global.css
  src/components/style/Navbar.scss
Labels: Ready for prod

#65 us works (when clicking on a county on the map, the name of the count…
  src/components/DataByCounty.js
  src/components/SearchBar.js
Labels: Ready for prod

#67 Graphic
  package-lock.json
  package.json
  src/components/Graphic.js
  src/components/Home.js
  src/components/style/DataByCounty.scss
  src/components/style/Graphic.scss
Labels: Ready for prod

#71 Comp04 form
  src/components/ContactForm.js
  src/components/style/ContactForm.scss
Labels: Ready for prod

#70 Info02 about us
  src/components/AboutUs.js
  src/components/ContactForm.js
  src/components/Home.js
  src/components/img/avatar1.jpeg
  src/components/img/avatar2.jpeg
  src/components/img/avatar3.jpeg
  src/components/img/avatar4.jpeg
  src/components/img/avatar5.jpeg
  src/components/style/AboutUs.scss
  src/components/style/News.scss
Labels: Ready for prod

#69 map with colors
  .eslintrc.json
  src/components/DataByCounty.js
  src/components/Map.js
  src/components/style/DataByCounty.scss
  src/components/style/Map.scss
Labels: Ready for prod

#68 Inf05 county modal - Ouverture d'une modal lors du clic sur un département du Top 5
  package-lock.json
  package.json
  src/App.scss
  src/components/Footer.js
  src/components/TopFive.js
  src/components/TopFiveCard.js
  src/components/TopFiveCountyModal.js
  src/components/datas/countyList.json
  src/components/img/face-mask-banner.png
  src/components/img/facebook-logo.png
  src/components/img/github-logo.png
  src/components/img/twitter-logo.png
  src/components/style/Banner.scss
  src/components/style/Footer.scss
  src/components/style/TopFive.scss
Labels: Ready for prod

#72 Sprint3 last fixes
  src/App.scss
  src/components/AboutUs.js
  src/components/Burger.js
  src/components/ContactForm.js
  src/components/DataByCounty.js
  src/components/DataCard.js
  src/components/Graphic.js
  src/components/Map.js
  src/components/Navbar.js
  src/components/News.js
  src/components/TopFiveCountyModal.js
  src/components/style/AboutUs.scss
  src/components/style/Banner.scss
  src/components/style/Burger.scss
  src/components/style/ContactForm.scss
  src/components/style/DataByCounty.scss
  src/components/style/Global.css
  src/components/style/Graphic.scss
  src/components/style/Map.scss
  src/components/style/Navbar.scss
  src/components/style/News.scss
  src/components/style/TopFive.scss
  src/components/style/WhereToGo.scss
Labels: Ready for prod

#77 Inf06 graphic checkboxes
  src/components/Graphic.js
  src/components/style/Graphic.scss
Labels: Ready for prod

#75 modification du css pour les boutons de ContactForm et TopFive : remo…
  src/components/style/ContactForm.scss
  src/components/style/TopFive.scss
Labels: Ready for prod

#76 Re06 color map sequel
  src/components/Map.js
  src/components/TopFiveCard.js
  src/components/dataConversion.js
  src/components/style/DataByCounty.scss
Labels: Ready for prod

#81 Geolocation
  package-lock.json
  package.json
  src/components/DataByCounty.js
  src/components/GeoLocation.js
  src/components/GeoLocationModal.js
  src/components/style/DataByCounty.scss
Labels: Ready for prod

#82 ajout du loader pendant le chargement de la page
  package-lock.json
  public/index.css
  public/index.html
  src/App.js
  src/components/Home.js
  src/components/Navbar.js
  src/components/style/ContactForm.scss
Labels: Ready for prod

#84 Na 06 store
  src/App.js
  src/components/Basket.js
  src/components/Burger.js
  src/components/ConfirmationModal.js
  src/components/Navbar.js
  src/components/ProductCard.js
  src/components/Store.js
  src/components/style/Basket.scss
  src/components/style/ProductCard.scss
  src/contexts/StoreContext.js
Labels: Ready for prod

#83 Ou sortir leaflet
  package-lock.json
  package.json
  public/index.html
  src/App.js
  src/components/Navbar.js
  src/components/Radius.js
  src/components/Searchaddress.js
  src/components/TopFive.js
  src/components/WhereToGo.js
  src/components/style/Footer.scss
  src/components/style/Navbar.scss
  src/components/style/Radius.scss
  src/components/style/TopFive.scss
  src/components/style/WhereToGo.scss
Labels: Ready for prod

#86 Changement des url des requêtes au serveur Node
  src/components/Basket.js
  src/components/ProductCard.js
  src/contexts/StoreContext.js
Labels: Ready for prod

#87 Connect contact form
  src/components/Basket.js
  src/components/ContactConfirmation.js
  src/components/ContactForm.js
Labels: Ready for prod

#92 Nicolas last fixes
  src/App.js
  src/components/Basket.js
  src/components/ContactForm.js
  src/components/Store.js
  src/contexts/StoreContext.js
Labels: Ready for prod

#88 updated navbar
  src/components/Burger.js
  src/components/Map.js
  src/components/Navbar.js
Labels: Ready for prod

#91 Graphcss
  src/App.js
  src/components/GeoLocation.js
  src/components/Graphic.js
  src/components/Store.js
  src/components/style/Graphic.scss
  src/contexts/StoreContext.js
Labels: Ready for prod

#94 Change api news
  src/components/Footer.js
  src/components/News.js
  src/components/style/AboutUs.scss
  src/components/style/News.scss
Labels: Ready for prod
